language: node_js
node_js:
  - "4"
  - "6"
  - "7"
script:
  - npm run build
  - npm run test:nocompile # already run schema and tsc in build
  - npm run check:schema
  - npm run check:examples
  - npm run codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache: yarn
notifications:
  email: never
  slack:
    rooms:
      - vega-js:eJe5JNgxfucTVcTMbeplKX3v
    on_success: never
    on_failure: always
cache:
  directories:
  - $HOME/.yarn-cache
