dist: trusty

language: node_js
node_js:
  - "10"

env:
  global:
    secure: I9sReagJiE7B0154AnU3t8WcdPtmZm86vMp+6umKegvzYr46jbypPAmlWW50A09fw4AmTaGOtwpYtvglf0JikkR6saXY0rRquDnO70DRmbdrO2o2WMjjCzkYID58SkGvqsqVJ4HXcu0HdJp6o5L7v7JMdzji6abYKxtsnw2ouk0=

matrix:
  include:
    - env: TEST_SCRIPT=build
    - env: TEST_SCRIPT=cover
    - env: TEST_SCRIPT=test
      addons:
        chrome: stable
    - env: TEST_SCRIPT=update

script: ./scripts/ci.sh $TEST_SCRIPT

cache: yarn

notifications:
  email: never
  slack:
    rooms:
      - vega-js:eJe5JNgxfucTVcTMbeplKX3v
    on_success: never
    on_failure: always
