dist: trusty
addons:
  chrome: stable

language: node_js
node_js:
  - "6"
  - "8"
env:
  LATEST=false
matrix:
  include:
    - node_js: "10"
      env: LATEST=true

before_install: |
  # Minimal installation as described in https://github.com/martinda/gnu-parallel
  wget http://git.savannah.gnu.org/cgit/parallel.git/plain/src/parallel
  chmod +x parallel
  cp parallel sem
  sudo mv parallel sem /usr/local/bin

script: |
  set -e
  yarn data
  if [ $LATEST = true ]; then
    yarn build
    yarn jest test/ --collectCoverage=true
    yarn codecov
    yarn jest examples/
    yarn test:runtime
    ./scripts/check-schema.sh
    ./scripts/check-and-fix.sh
    yarn lint
  else
    yarn build:only
    yarn jest
    yarn test:runtime
  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache: yarn
