dist: trusty
addons:
  chrome: stable

language: node_js
node_js:
  - "8"
  - "10"
env: LATEST=false
matrix:
  include:
    - node_js: "11" # Update version in check-and-fix.sh as well.
      env: LATEST=true

before_install: |
  # install new gnu parallel since apt doesn't have a recent version
  wget https://ftp.gnu.org/gnu/parallel/parallel-20190122.tar.bz2
  tar xjf parallel-20190122.tar.bz2
  cd parallel-20190122
  ./configure
  sudo make install

script: |
  yarn
  set -ex
  yarn data
  if [ $LATEST = true ]; then
    yarn build
    yarn jest test/ --collectCoverage=true
    yarn codecov
    yarn jest examples/
    yarn test:runtime
    ./scripts/check-schema.sh
    ./scripts/check-and-fix.sh
    yarn lint
  else
    yarn build:only
    yarn test:runtime
    yarn jest test/ examples/
  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache: yarn

env:
  global:
    secure: I9sReagJiE7B0154AnU3t8WcdPtmZm86vMp+6umKegvzYr46jbypPAmlWW50A09fw4AmTaGOtwpYtvglf0JikkR6saXY0rRquDnO70DRmbdrO2o2WMjjCzkYID58SkGvqsqVJ4HXcu0HdJp6o5L7v7JMdzji6abYKxtsnw2ouk0=
