dist: trusty
addons:
  chrome: stable

language: node_js
node_js:
  - "6"
  - "8"

before_install:
  # Minimal installation as desdcribed in https://github.com/martinda/gnu-parallel
  - wget http://git.savannah.gnu.org/cgit/parallel.git/plain/src/parallel
  - chmod +x parallel
  - cp parallel sem
  - sudo mv parallel sem /usr/local/bin

script:
  - npm run build
  - npm run test:nocompile # already run schema and tsc in build
  - npm run data
  - npm run build:examples-only
  - npm run check:schema
  - npm run check:examples
  - npm run codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache: yarn

notifications:
  email: never
  slack:
    rooms:
      - vega-js:eJe5JNgxfucTVcTMbeplKX3v
    on_success: never
    on_failure: always
