language: node_js
node_js:
  - "4"
  - "6"
  - "7"
script:
  - npm run build
  - npm run test:noschema # already run schema in build
  - npm run codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache: yarn
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - 'uwdub:Ry6mwlUX1aZevqiqmYLiA3N1'
    on_success: never
    on_failure: change
cache:
  directories:
  - $HOME/.yarn-cache
