jobs:
- job: Node 6
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: NodeTool@0
    inputs:
      version: 6.x
    displayName: 'Install Node.js'

  - script: |
      yarn
    displayName: 'Install dependencies'

  - script: |
      yarn data
      yarn build:only
    displayName: 'Build'

  - script: |
      yarn jest
      yarn test:runtime
    displayName: 'Test'

- job: Build
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: NodeTool@0
    inputs:
      version: 8.x
    displayName: 'Install Node.js'

  - script: |
      wget http://git.savannah.gnu.org/cgit/parallel.git/plain/src/parallel
      chmod +x parallel
      cp parallel sem
      sudo mv parallel sem /usr/local/bin
      yarn
    displayName: 'Install dependencies'

  - script: |
      yarn data
      yarn build
    displayName: 'Build'

- job: Test
  dependsOn:
    - Build

  steps:
  - script: |
      JEST_JUNIT_OUTPUT="./TEST-main.xml" yarn jest test/ --ci --reporters=default --reporters=jest-junit --collectCoverage=true
      yarn codecov
      JEST_JUNIT_OUTPUT="./TEST-examples.xml" yarn jest examples/ --ci --reporters=default --reporters=jest-junit 
      yarn test:runtime
      yarn lint
    displayName: 'Test'

  - task: PublishTestResults@2

  - script: bash <(curl -s https://codecov.io/bash)
    displayName: 'Coverage report'

- job: Check and Fix
  dependsOn:
    - Build

  - script: |
      ./scripts/check-schema.sh
      ./scripts/check-and-fix.sh
    displayName: 'Check and Fix'
