name: Check

on:
  workflow_dispatch:
  push:

jobs:
  check:
    name: Format, Schema, and Examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}
          ref: ${{ github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Setup data
        run: yarn data

      - name: Install Parallel
        run: |
          # Faster than "sudo apt-get install parallel"
          wget https://raw.githubusercontent.com/martinda/gnu-parallel/master/src/parallel
          chmod +x parallel
          cp parallel sem
          sudo mv parallel sem /usr/local/bin

      - name: Format
        run: yarn format

      - name: Build Schema
        run: yarn schema

      - name: Check Schema
        run: scripts/check-schema.sh

      - name: Setup Git remote
        run: scripts/setup-git-ci.sh

      - name: Check and Commit
        run: scripts/check-and-commit.sh
