name: Check

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  check:
    name: Lint, Format, Schema, and Examples
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Install Parallel
        run: |
          # Faster than "sudo apt-get install parallel"
          wget https://raw.githubusercontent.com/martinda/gnu-parallel/master/src/parallel
          chmod +x parallel
          cp parallel sem
          sudo mv parallel sem /usr/local/bin

      - name: Lint
        if: github.ref == 'refs/heads/master'
        run: yarn lint

      - name: Format
        if: github.ref != 'refs/heads/master'
        run: yarn format

      - name: Build Schema
        run: yarn schema

      - name: Check Schema
        run: ./scripts/check-schema.sh

      - name: Setup Git remote
        run: ./scripts/setup-git-ci.sh
        if: github.event.pull_request.head.repo.full_name == github.repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Check and Commit
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: ./scripts/check-and-commit.sh

  toc:
    name: TOC

    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push to the branch.
    if: "!contains(github.event.head_commit.message, '[CI]') && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: Setup data
        run: yarn data

      - name: Build Jekyll
        run: |
          gem install bundler
          pushd site
          bundle install
          bundle exec jekyll build -q
          popd

      - name: Build TOC
        run: scripts/generate-toc

      - name: Setup Git remote
        run: ./scripts/setup-git-ci.sh
        if: github.event.pull_request.head.repo.full_name == github.repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Check and Commit
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: ./scripts/check-and-commit-toc.sh
