name: Publish Documentation and Schema

on:
  release:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    # The "published" event includes both releases and prereleases
    # use "released" to limit triggers to official releases
    types: [released]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Setup Git remote
        run: scripts/setup-git-ci.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add schema repo
        run: |
          pushd ..
          git clone https://x-access-token:${GH_PAT}@github.com/vega/schema.git
          popd
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Prebuild website
        run: yarn predeploy:site

      - name: Publish website
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: 'site/'

      - name: Publish schema
        run: scripts/deploy-schema.sh
