name: Test Docs

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - stable
    paths-ignore:
      - 'src/**'
  pull_request:

jobs:
  build-site:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:site
