name: Test Docs

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'site/**'
      - 'yarn.lock'
      - '**prettier**'

jobs:
  build-site:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn prettierbase --check

      - name: Build
        run: yarn build:site
